#!/usr/bin/python

def dump_keys(in_file):
    keys = set()

    def extract_key(line):
        keys.add(line[0])

    try:
        with open(in_file,"r") as f:
            for line in f:
                extract_key(line.strip().split(','))
    except:
        print "Warning: unable to extract all keys."
    
    print "Extracted %s keys from %s." % (len(keys), in_file)
    with open("key_dump.dat","w") as f:
        for i in range(5000):
            f.write(keys.pop() + "\n")

if __name__ == '__main__':
    dump_keys("/home/ubuntu/efs/smallkv/12.5GB/data_0.csv")
    dump_keys("/home/ubuntu/efs/smallkv/12.5GB/data_2.csv")
